### ISSUE TITLE
[Music] Remove Extra Messages

### ISSUE THREAD

**Issue by ghost** [miraai/LunaBot#12]
In the below screenshot, `[11:13 AM] BOTLuna: Please wait. Collecting information...` should be deleted after the next message sends. It's no longer needed after it gives the info. 😛 

![img](http://i.imgur.com/C34wj9V.png)

**Comment by ghost** [comment]
On that note...

![img](http://i.imgur.com/xBoN47q.png)

I think this message could either be deleted or edited to say "now playing blah blah blah song" or something.

**Comment by miraai** [comment]
Done :+1:
